### ISSUE TITLE
AggregateError

### ISSUE THREAD

**Issue by dawid86** [mihaeu/cosmere#46]
Hello!

While using cosmere I'm getting this error:

>×  fatal     AggregateError
```
    at AxiosError.from (<pathToNpm>\npm\node_modules\cosmere\node_modules\axios\dist\node\axios.cjs:836:14)
    at RedirectableRequest.handleRequestError (<pathToNpm>\npm\node_modules\cosmere\node_modules\axios\dist\node\axios.cjs:3086:25)
    at RedirectableRequest.emit (node:events:518:28)
    at eventHandlers.<computed> (<pathToNpm>\npm\node_modules\cosmere\node_modules\follow-redirects\index.js:38:24)
    at ClientRequest.emit (node:events:518:28)
    at Socket.socketErrorListener (node:_http_client:500:9)
    at Socket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
    at Axios.request (<pathToNpm>\npm\node_modules\cosmere\node_modules\axios\dist\node\axios.cjs:3876:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ConfluenceAPI.getAttachments (<pathToNpm>\npm\node_modules\cosmere\dist\src\api\ConfluenceAPI.js:56:17)
    at async updateAttachments (<pathToNpm>\npm\node_modules\cosmere\dist\src\UpdatePage.js:120:32)
    at async updatePage (<pathToNpm>\npm\node_modules\cosmere\dist\src\UpdatePage.js:186:18)
    at async Object.default_1 [as default] (<pathToNpm>\npm\node_modules\cosmere\dist\src\cli\MainCommand.js:10:9)
```

can you please support?

Thx!

**Comment by mihaeu** [comment]
Hi there :wave: without further information it is very hard to help you.

Is the problem reproducible? What version of node are you using? What step does it fail on.

**Comment by dawid86** [comment]
Hi @mihaeu !

thank you for your reply.

I'm getting this error at the second (I think) step:

```
►  start     Starting to render "{pathToMdFile}\{mdFileName}.md"
×  fatal     AggregateError
```

I am on version 10.5.2 of npm.

The problem occurs every time I'm running cosmere.

**Comment by dawid86** [comment]
@mihaeu - closing issue. I missed _baseUrl_ property in cosmere config JSON. When I add it, all works properly :)
